### PR TITLE
Implement correct reference reader

### PR DESCRIPTION
**Pull request by smacker**
I didn't really get why you changed get references reader using `git` instead of `go-git`.
Anyway, I didn't touch that if statement, just corrected reader itself.

* Return commit hash

Engine hides real reference hash and always returns commit hash, but here I return both of them.

Resolving correct commit hash is a bit tricky with go git.
Reference can be symbolic and it can be a tag.
I handle both cases and validated results using engine.

* Add isRemote flag

Validation output:
Engine: https://gist.github.com/smacker/4af884632182a38e7fe886a018c6e76a
This PR (without `if` for references in`shardInfo`): https://gist.github.com/smacker/c2df9045a058d54af01a6c92935d465b

I don't remove `remotes` prefix from a name, but we can do it later if we need.

Thanks!

### CODE REVIEW

**Comment by eiso** [comment]
I won't be able to merge this yet since the `references` data source needs to have all of the parent commits for each reference. This works fine when you're going from references to blobs but won't allow you to get all commits that are in a specific branch.

I will leave it open because the way to properly implement this is using https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/revlist.

**Comment by smacker** [comment]
Please check again.

Here is an output: https://gist.github.com/smacker/8ae35906f53be52006074fe304f7702c
Here is an output of `git rev-list` for master branch: https://gist.github.com/smacker/ef49cbcfc43bc14532bb6a0e28b07584

The difference is it doesn't ignore symbolic references.
Also now because it compatible with what you did by `git rev-list`, I removed `if` from `shardInfo`

**Comment by eiso** [comment]
Can you update that gist, using `git rev-list --children $COMMIT | cut -d ' ' -f 1 | uniq` so I can compare them side-by-side.

**Comment by smacker** [comment]
`$ git rev-list --children 309d167aff739698fc297974663516a023b3a499 | cut -d ' ' -f 1 | uniq`:
https://gist.github.com/smacker/75cc784884854d423a2839a58122c540

**Pull request merged**
